spring:
  main:
    banner-mode: "off"

client:
  HelloWorldService:
    address: https://localhost:8080/services/hello

ssl:
  trust-store: /opt/development/workspaces/antoniocaccamo/cxf-prime/certificates/client/cxf-prime-client-1.keystore
  trust-store-password: Passw0rd!
