spring:
  main:
    banner-mode: "off"

server:
  port: 8090
  ssl:
    enabled: true
#    client-auth: true    # mutual authentication
    key-store: /development/workspaces/antoniocaccamo/cxf-prime/certificates/server/cxf-prime-server.keystore
    key-alias: cxf-prime-server
    key-password: Passw0rd!

wss4j:
  enabled: true
  callback:
    keypairs:  cxf-prime-server , Passw0rd! | cxf-prime-client-1 , Passw0rd! | cxf-prime-client-2 , Passw0rd!
  encrypt:
    username: useReqSigCert
    file : wss/encrypt.properties
  signature:
    username: cxf-prime-server
    file : wss/signature.properties
