spring:
  main:
    banner-mode: "off"

cxf:
  path : /services


server:
  port: 8080
  ssl:
    key-store: /opt/development/workspaces/antoniocaccamo/cxf-prime/certificates/server/cxf-prime-server.keystore
    key-alias: cxf-prime-server
    key-password: Passw0rd!

security:
  require-ssl: true

wss4j:
  enabled: true
  key-store: /opt/development/workspaces/antoniocaccamo/cxf-prime/certificates/server/cxf-prime-server.keystore
  key-alias: cxf-prime-server
  key-password: Passw0rd!
